spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      database: postgresql
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
      database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  rabbitmq:
    host: localhost
    port: 5672  # RabbitMQ port
    username: guest
    password: guest
    virtual-host: /
  data:
    mongodb:
#      host: ${MONGODB_HOST}
#      port: ${MONGODB_PORT}
#      database: ${MONGODB_DB}
      username: ${MONGODB_USER}
      password: ${MONGODB_PWD}
      authentication-database: ${MONGODB_AUTH_DB}
      uri: ${MONGODB_URI}

jwt:
  secret: ${JWT_SECRET}